apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/counter
          ports:
            - containerPort: 8000
          env:
            - name: BACKEND
              value: inmemory
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 40Mi
